//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexColumnizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegexColumnizer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Regex !{0}{1}.
        /// </summary>
        public static string RegexColumnizer_ConfigDialog_Error_Message_InvalidRegex {
            get {
                return ResourceManager.GetString("RegexColumnizer_ConfigDialog_Error_Message_InvalidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration directory cannot be null or empty.
        /// </summary>
        public static string RegexColumnizer_Configuration_DirectoryCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("RegexColumnizer_Configuration_DirectoryCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns are filled by regular expression named capture groups.
        /// </summary>
        public static string RegexColumnizer_Description {
            get {
                return ResourceManager.GetString("RegexColumnizer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columnizer name cannot be null or empty.
        /// </summary>
        public static string RegexColumnizer_Error_Message_ColumnizerNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("RegexColumnizer_Error_Message_ColumnizerNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columnizer name &apos;{0}&apos; contains invalid filename characters.
        /// </summary>
        public static string RegexColumnizer_Error_Message_ColumnizerNameNameContainsInvalidFilenameCharacters {
            get {
                return ResourceManager.GetString("RegexColumnizer_Error_Message_ColumnizerNameNameContainsInvalidFilenameCharacters" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columnizer name &apos;{0}&apos; contains path separators which are not allowed.
        /// </summary>
        public static string RegexColumnizer_Error_Message_ColumnizerNameNameContainsPathSeparatorsWhichAreNotAllowed {
            get {
                return ResourceManager.GetString("RegexColumnizer_Error_Message_ColumnizerNameNameContainsPathSeparatorsWhichAreNot" +
                        "Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columnizer name &apos;{0}&apos; contains path traversal patterns which are not allowed.
        /// </summary>
        public static string RegexColumnizer_Error_Message_ColumnizerNameNameContainsPathTraversalPatternsWhichAreNotAllowed {
            get {
                return ResourceManager.GetString("RegexColumnizer_Error_Message_ColumnizerNameNameContainsPathTraversalPatternsWhic" +
                        "hAreNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create configuration directory: {0}.
        /// </summary>
        public static string RegexColumnizer_UI_Message_FailedToCreateConfigurationDirectory {
            get {
                return ResourceManager.GetString("RegexColumnizer_UI_Message_FailedToCreateConfigurationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save configuration: {0}.
        /// </summary>
        public static string RegexColumnizer_UI_Message_FailedToSaveConfiguration {
            get {
                return ResourceManager.GetString("RegexColumnizer_UI_Message_FailedToSaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regex pattern: {0}.
        /// </summary>
        public static string RegexColumnizer_UI_Message_InvalidRegexPattern {
            get {
                return ResourceManager.GetString("RegexColumnizer_UI_Message_InvalidRegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex pattern may cause performance issues: {0}.
        /// </summary>
        public static string RegexColumnizer_UI_Message_RegexTimeout {
            get {
                return ResourceManager.GetString("RegexColumnizer_UI_Message_RegexTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialize.
        /// </summary>
        public static string RegexColumnizer_UI_Title_Deserialize {
            get {
                return ResourceManager.GetString("RegexColumnizer_UI_Title_Deserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error.
        /// </summary>
        public static string RegexColumnizer_UI_Title_Error {
            get {
                return ResourceManager.GetString("RegexColumnizer_UI_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Warning.
        /// </summary>
        public static string RegexColumnizer_UI_Title_Warning {
            get {
                return ResourceManager.GetString("RegexColumnizer_UI_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RegexColumnizerConfigDialog_UI_Button_Cancel {
            get {
                return ResourceManager.GetString("RegexColumnizerConfigDialog_UI_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string RegexColumnizerConfigDialog_UI_Button_Check {
            get {
                return ResourceManager.GetString("RegexColumnizerConfigDialog_UI_Button_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string RegexColumnizerConfigDialog_UI_Button_OK {
            get {
                return ResourceManager.GetString("RegexColumnizerConfigDialog_UI_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex Columnizer Configuration.
        /// </summary>
        public static string RegexColumnizerConfigDialog_UI_Error_Title {
            get {
                return ResourceManager.GetString("RegexColumnizerConfigDialog_UI_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Zone.
        /// </summary>
        public static string RegexColumnizerConfigDialog_UI_GroupBox_TestZone {
            get {
                return ResourceManager.GetString("RegexColumnizerConfigDialog_UI_GroupBox_TestZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string RegexColumnizerConfigDialog_UI_Label_Line {
            get {
                return ResourceManager.GetString("RegexColumnizerConfigDialog_UI_Label_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RegexColumnizerConfigDialog_UI_Label_Name {
            get {
                return ResourceManager.GetString("RegexColumnizerConfigDialog_UI_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string RegexColumnizerConfigDialog_UI_Label_Regex {
            get {
                return ResourceManager.GetString("RegexColumnizerConfigDialog_UI_Label_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex Columnizer.
        /// </summary>
        public static string RegexColumnizerConfigDialog_UI_Title {
            get {
                return ResourceManager.GetString("RegexColumnizerConfigDialog_UI_Title", resourceCulture);
            }
        }
    }
}
