//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SftpFileSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogExpert.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file....
        /// </summary>
        public static string ConfigDialog_UI_Button_SelectFile {
            get {
                return ResourceManager.GetString("ConfigDialog_UI_Button_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use keyfile.
        /// </summary>
        public static string ConfigDialog_UI_CheckBox_UseKeyfile {
            get {
                return ResourceManager.GetString("ConfigDialog_UI_CheckBox_UseKeyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key type.
        /// </summary>
        public static string ConfigDialog_UI_GroupBox_KeyType {
            get {
                return ResourceManager.GetString("ConfigDialog_UI_GroupBox_KeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key will be loaded once on first usage. Password will be asked then..
        /// </summary>
        public static string ConfigDialog_UI_Label_KeyInfo {
            get {
                return ResourceManager.GetString("ConfigDialog_UI_Label_KeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putty private key.
        /// </summary>
        public static string ConfigDialog_UI_RadioButton_PuttyKey {
            get {
                return ResourceManager.GetString("ConfigDialog_UI_RadioButton_PuttyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open SSH private key.
        /// </summary>
        public static string ConfigDialog_UI_RadioButton_SSHKey {
            get {
                return ResourceManager.GetString("ConfigDialog_UI_RadioButton_SSHKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFTP Configuration.
        /// </summary>
        public static string ConfigDialog_UI_Title {
            get {
                return ResourceManager.GetString("ConfigDialog_UI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FailedKeyDialog_UI_Button_Cancel {
            get {
                return ResourceManager.GetString("FailedKeyDialog_UI_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry with key.
        /// </summary>
        public static string FailedKeyDialog_UI_Button_Retry {
            get {
                return ResourceManager.GetString("FailedKeyDialog_UI_Button_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use password authentication.
        /// </summary>
        public static string FailedKeyDialog_UI_Button_UsePassword {
            get {
                return ResourceManager.GetString("FailedKeyDialog_UI_Button_UsePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key authentication failed. What would you like to do?.
        /// </summary>
        public static string FailedKeyDialog_UI_Label_Message {
            get {
                return ResourceManager.GetString("FailedKeyDialog_UI_Label_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Authentication Failed.
        /// </summary>
        public static string FailedKeyDialog_UI_Title {
            get {
                return ResourceManager.GetString("FailedKeyDialog_UI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LoginDialog_UI_Button_Cancel {
            get {
                return ResourceManager.GetString("LoginDialog_UI_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LoginDialog_UI_Button_OK {
            get {
                return ResourceManager.GetString("LoginDialog_UI_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LoginDialog_UI_Label_Password {
            get {
                return ResourceManager.GetString("LoginDialog_UI_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string LoginDialog_UI_Label_Server {
            get {
                return ResourceManager.GetString("LoginDialog_UI_Label_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string LoginDialog_UI_Label_Username {
            get {
                return ResourceManager.GetString("LoginDialog_UI_Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogExpert SFTP Plugin.
        /// </summary>
        public static string LoginDialog_UI_Title {
            get {
                return ResourceManager.GetString("LoginDialog_UI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PrivateKeyPasswordDialog_UI_Button_Cancel {
            get {
                return ResourceManager.GetString("PrivateKeyPasswordDialog_UI_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string PrivateKeyPasswordDialog_UI_Button_OK {
            get {
                return ResourceManager.GetString("PrivateKeyPasswordDialog_UI_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter private key password:.
        /// </summary>
        public static string PrivateKeyPasswordDialog_UI_Label_Password {
            get {
                return ResourceManager.GetString("PrivateKeyPasswordDialog_UI_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key Password.
        /// </summary>
        public static string PrivateKeyPasswordDialog_UI_Title {
            get {
                return ResourceManager.GetString("PrivateKeyPasswordDialog_UI_Title", resourceCulture);
            }
        }
    }
}
