<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>

    <RootNamespace>SftpFileSystem</RootNamespace>
    <AssemblyName>SftpFileSystem</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <OutputPath>$(SolutionDir)..\bin\$(Configuration)\plugins</OutputPath>
    <AssemblyTitle>SftpFileSystem</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ColumnizerLib\ColumnizerLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SSH.NET" />
  </ItemGroup>

</Project>
