<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <OutputPath>$(LogExpertPluginsDirectory)</OutputPath>
    <AssemblyTitle>GlassfishColumnizer</AssemblyTitle>
    <Description>Glassfish logfile support for LogExpert</Description>
    <RootNamespace>GlassfishColumnizer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ColumnizerLib\ColumnizerLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="GlassfishColumnizer.manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
