<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>

    <IsTestProject>true</IsTestProject>
    
    
    <OutputPath>bin\$(Configuration)</OutputPath>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <PropertyGroup>
    
  </PropertyGroup>
  <PropertyGroup>
    
    <AssemblyTitle>RegexColumnizer.UnitTests</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ColumnizerLib\ColumnizerLib.csproj" />
    <ProjectReference Include="..\RegexColumnizer\RegexColumnizer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>
</Project>
