<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <OutputPath>$(SolutionDir)..\bin\$(Configuration)\plugins</OutputPath>
    <AssemblyTitle>JsonColumnizer</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ColumnizerLib\ColumnizerLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

</Project>
