<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <AssemblyTitle>LogExpert.Persister.Tests</AssemblyTitle>
    <RootNamespace>LogExpert.Persister.Tests</RootNamespace>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Moq" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LogExpert.Core\LogExpert.Core.csproj" />
      <ProjectReference Include="..\PluginRegistry\LogExpert.PluginRegistry.csproj" />
    </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
