<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <DocumentationFile>$(LogExpertDocsDirectory)ColumnizerLib.xml</DocumentationFile>

    <RootNamespace>ColumnizerLib</RootNamespace>

    <PackageId>LogExpert.ColumnizerLib</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>ColumnizerLib</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

</Project>
