//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log4jXmlColumnizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogExpert.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Log4jXmlColumnizerConfigDlg_UI_Button_Cancel {
            get {
                return ResourceManager.GetString("Log4jXmlColumnizerConfigDlg_UI_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Log4jXmlColumnizerConfigDlg_UI_Button_OK {
            get {
                return ResourceManager.GetString("Log4jXmlColumnizerConfigDlg_UI_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert timestamps to local time zone.
        /// </summary>
        public static string Log4jXmlColumnizerConfigDlg_UI_CheckBox_LocalTime {
            get {
                return ResourceManager.GetString("Log4jXmlColumnizerConfigDlg_UI_CheckBox_LocalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Log4jXmlColumnizerConfigDlg_UI_ColumnHeader_Column {
            get {
                return ResourceManager.GetString("Log4jXmlColumnizerConfigDlg_UI_ColumnHeader_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max len.
        /// </summary>
        public static string Log4jXmlColumnizerConfigDlg_UI_ColumnHeader_MaxLen {
            get {
                return ResourceManager.GetString("Log4jXmlColumnizerConfigDlg_UI_ColumnHeader_MaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Log4jXmlColumnizerConfigDlg_UI_ColumnHeader_Visible {
            get {
                return ResourceManager.GetString("Log4jXmlColumnizerConfigDlg_UI_ColumnHeader_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose columns to show:.
        /// </summary>
        public static string Log4jXmlColumnizerConfigDlg_UI_Label_ChooseColumns {
            get {
                return ResourceManager.GetString("Log4jXmlColumnizerConfigDlg_UI_Label_ChooseColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log4j XML Columnizer.
        /// </summary>
        public static string Log4jXmlColumnizerConfigDlg_UI_Title {
            get {
                return ResourceManager.GetString("Log4jXmlColumnizerConfigDlg_UI_Title", resourceCulture);
            }
        }
    }
}
