<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <AssemblyTitle>AutoColumnizer</AssemblyTitle>
    <OutputPath>$(SolutionDir)..\bin\$(Configuration)\plugins</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ColumnizerLib\ColumnizerLib.csproj" />
  </ItemGroup>

</Project>
