<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <AssemblyTitle>AutoColumnizer</AssemblyTitle>
    <OutputPath>$(SolutionDir)..\bin\$(Configuration)\plugins</OutputPath>
    <RootNamespace>AutoColumnizer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ColumnizerLib\ColumnizerLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="AutoColumnizer.manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
