<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsTestProject>true</IsTestProject>
    <AssemblyTitle>ColumnizerLib.UnitTests</AssemblyTitle>
    <Company>Microsoft</Company>
    <OutputPath>bin\$(Configuration)</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ColumnizerLib\ColumnizerLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>
</Project>
