; =============================================================================
; AUTO-GENERATED by the Nuke GenerateInstallerFileList target. DO NOT EDIT BY HAND.
;
; Ships exactly the runtime assemblies declared in LogExpert.deps.json (the app's
; dependency closure). Driven by deps.json rather than the raw bin/Release listing so
; stray files from other projects that share the output folder (e.g. BenchmarkDotNet's
; System.Management) are not shipped. Regression guard for #634 (LogExpert.Audio/NAudio
; were missing from the former hand-maintained list).
; =============================================================================

Source: "{#ReleaseFolder}\ColumnizerLib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.Audio.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.Configuration.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.PluginRegistry.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.Resources.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.UI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Microsoft.Win32.SystemEvents.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\NAudio.Asio.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\NAudio.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\NAudio.Midi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\NAudio.Wasapi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\NAudio.WinForms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\NAudio.WinMM.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\NAudio.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\NLog.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\NuGet.Versioning.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\System.CommandLine.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\System.Drawing.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\System.Formats.Nrbf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\System.Private.Windows.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\System.Private.Windows.GdiPlus.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\System.Resources.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.ComCtl32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Cryptography.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Gdi32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Kernel32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Ole.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Rpc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.RstrtMgr.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Security.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Shell32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.ShlwApi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.User32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\WeifenLuo.WinFormsUI.Docking.ThemeVS2015.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\WeifenLuo.WinFormsUI.Docking.dll"; DestDir: "{app}"; Flags: ignoreversion
