; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#include "CodeDependencies.iss"

#define AppName "LogExpert"
#define AppVersion "1.21.0"
#define AppURL "https://github.com/LogExperts/LogExpert"
#define AppExeName "LogExpert.exe"

; Path of the inno setup file
#define AppPath SourcePath
#define SetupName "LogExpert.Installer"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9C6E17B8-912C-45F9-9E7F-49CEAD8D6D7A}
AppName={#AppName}

; Version Information
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}

AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
DefaultDirName={pf}\{#AppName}
DefaultGroupName={#AppName}
AllowNoIcons=yes

LicenseFile=..\..\LICENSE
;InfoBeforeFile=..\..\CHANGELOG.md
;InfoAfterFile=..\..\README.md
OutputDir=..\..\bin\

OutputBaseFilename={#SetupName}.{#SetupSetting("AppVersion")}
SetupIconFile={#AppPath}..\LogExpert.Resources\images\icons\logexpert.ico
Compression=lzma2/normal
SolidCompression=yes

; GUI Style, classic or modern
WizardStyle=modern
UsePreviousAppDir=True
DisableWelcomePage=False
ShowTasksTreeLines=True
AlwaysShowGroupOnReadyPage=True
AlwaysShowDirOnReadyPage=True

; needs to be set to false, so reinstalls still show the folder selection
DisableDirPage=False

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\..\bin\Release\Licenses\*"; DestDir: "{app}\Licenses\"; Flags: ignoreversion recursesubdirs createallsubdirs

;Plugins

;DLLS for CSV Suppport
Source: "..\..\bin\Release\plugins\CsvHelper.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\pluginsx86\CsvHelper.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\CsvColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\pluginsx86\CsvColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\de\CsvColumnizer.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "..\..\bin\Release\pluginsx86\de\CsvColumnizer.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "..\..\bin\Release\plugins\CsvColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\pluginsx86\CsvColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "..\..\bin\Release\plugins\AutoColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\AutoColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "..\..\bin\Release\plugins\de\ColumnizerLib.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "..\..\bin\Release\plugins\ColumnizerLib.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion
Source: "..\..\bin\Release\plugins\ColumnizerLib.xml"; DestDir: "{app}\plugins\"; Flags: ignoreversion

Source: "..\..\bin\Release\pluginsx86\de\ColumnizerLib.resources.dll"; DestDir: "{app}\pluginsx86\de\"; Flags: ignoreversion
Source: "..\..\bin\Release\pluginsx86\ColumnizerLib.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion
Source: "..\..\bin\Release\pluginsx86\ColumnizerLib.xml"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion

Source: "..\..\bin\Release\plugins\BouncyCastle.Cryptography.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\Microsoft.Extensions.DependencyInjection.Abstractions"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\pluginsx86\Microsoft.Extensions.DependencyInjection.Abstractions"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\pluginsx86\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "..\..\bin\Release\plugins\Newtonsoft.Json.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\pluginsx86\Newtonsoft.Json.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "..\..\bin\Release\plugins\Microsoft.Bcl.HashCode.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\Renci.SshNet.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\System.Memory.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\System.Numerics.Vectors.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\System.Threading.Tasks.Extensions.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "..\..\bin\Release\plugins\DefaultPlugins.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\FlashIconHighlighter.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\FlashIconHighlighter.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "..\..\bin\Release\plugins\GlassfishColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\GlassfishColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "..\..\bin\Release\plugins\JsonColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\JsonColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "..\..\bin\Release\plugins\JsonCompactColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\de\JsonCompactColumnizer.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "..\..\bin\Release\plugins\JsonCompactColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "..\..\bin\Release\plugins\Log4jXmlColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\de\Log4jXmlColumnizer.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "..\..\bin\Release\plugins\Log4jXmlColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "..\..\bin\Release\plugins\RegexColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\de\RegexColumnizer.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "..\..\bin\Release\plugins\RegexColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "..\..\bin\Release\plugins\LogExpert.Core.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion

; DLLS for SFTP Support
Source: "..\..\bin\Release\plugins\SftpFileSystem.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\pluginsx86\SftpFileSystem.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\SftpFileSystem.Resources.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\pluginsx86\SftpFileSystem.Resources.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\de\SftpFileSystem.Resources.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "..\..\bin\Release\pluginsx86\de\SftpFileSystem.Resources.resources.dll"; DestDir: "{app}\pluginsx86\de\"; Flags: ignoreversion
Source: "..\..\bin\Release\plugins\SftpFileSystem.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\pluginsx86\SftpFileSystem.manifest.json"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\plugins\Renci.SshNet.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\..\bin\Release\pluginsx86\Renci.SshNet.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "..\..\bin\Release\de\ColumnizerLib.resources.dll"; DestDir: "{app}\de\"; Flags: ignoreversion
Source: "..\..\bin\Release\ColumnizerLib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\ColumnizerLib.xml"; DestDir: "{app}"; Flags: ignoreversion

; LogExpert Files
Source: "..\..\bin\Release\files\json\usedComponents.json"; DestDir: "{app}\files\json\"; Flags: ignoreversion
Source: "..\..\bin\Release\LogExpert.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\LogExpert.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\de\LogExpert.Configuration.resources.dll"; DestDir: "{app}\de\"; Flags: ignoreversion
Source: "..\..\bin\Release\LogExpert.Configuration.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\LogExpert.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\LogExpert.UI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\LogExpert.Resources.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\de\LogExpert.Resources.resources.dll"; DestDir: "{app}\de\"; Flags: ignoreversion
Source: "..\..\bin\Release\LogExpert.PluginRegistry.dll"; DestDir: "{app}"; Flags: ignoreversion

Source: "..\..\bin\Release\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\NuGet.Versioning.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\LogExpert.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\NLog.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\Start.cmd"; DestDir: "{app}"; Flags: ignoreversion

; Vanara libs for Pinvoke => https://github.com/dahall/Vanara
Source: "..\..\bin\Release\fr\Vanara.Core.resources.dll"; DestDir: "{app}\fr\"; Flags: ignoreversion
Source: "..\..\bin\Release\Vanara.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\Vanara.PInvoke.ComCtl32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\Vanara.PInvoke.Cryptography.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\Vanara.PInvoke.Gdi32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\Vanara.PInvoke.Kernel32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\Vanara.PInvoke.Ole.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\Vanara.PInvoke.Rpc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\Vanara.PInvoke.RstrtMgr.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\Vanara.PInvoke.Security.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\Vanara.PInvoke.Shell32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\Vanara.PInvoke.ShlwApi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\Vanara.PInvoke.User32.dll"; DestDir: "{app}"; Flags: ignoreversion

; GUI Libs
Source: "..\..\bin\Release\WeifenLuo.WinFormsUI.Docking.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\WeifenLuo.WinFormsUI.Docking.ThemeVS2015.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function InitializeSetup(): Boolean;
begin
    Dependency_AddDotNet100Desktop
    Result := True;
end;
