; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#include "CodeDependencies.iss"

#define AppName "LogExpert"
#define AppURL "https://github.com/LogExperts/LogExpert"
#define AppExeName "LogExpert.exe"

; Path of the inno setup file
#define AppPath SourcePath
#define SetupName "LogExpert.Installer"
#define ReleaseFolder = "..\..\bin\Release"

; AppVersion can be passed via command line (e.g., iscc /dAppVersion="1.21.0").
; The Nuke build system does this automatically using GitVersion.
; If not provided, it is read from the built executable's file version.
#ifndef AppVersion
  #define AppVersion GetFileVersion(AddBackslash(SourcePath) + ReleaseFolder + "\" + AppExeName)
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9C6E17B8-912C-45F9-9E7F-49CEAD8D6D7A}
AppName={#AppName}

; Version Information
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}

AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
DefaultDirName={commonpf}\{#AppName}
DefaultGroupName={#AppName}
AllowNoIcons=yes

LicenseFile=..\..\LICENSE
;InfoBeforeFile=..\..\CHANGELOG.md
;InfoAfterFile=..\..\README.md
OutputDir=..\..\bin\

OutputBaseFilename={#SetupName}.{#SetupSetting("AppVersion")}
SetupIconFile={#AppPath}..\LogExpert.Resources\images\icons\logexpert.ico
Compression=lzma2/normal
SolidCompression=yes

; GUI Style, classic or modern
WizardStyle=modern
UsePreviousAppDir=True
DisableWelcomePage=False
ShowTasksTreeLines=True
AlwaysShowGroupOnReadyPage=True
AlwaysShowDirOnReadyPage=True

; needs to be set to false, so reinstalls still show the folder selection
DisableDirPage=False

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#ReleaseFolder}\Licenses\*"; DestDir: "{app}\Licenses\"; Flags: ignoreversion recursesubdirs createallsubdirs

;Plugins

;DLLS for CSV Suppport
Source: "{#ReleaseFolder}\plugins\CsvHelper.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\pluginsx86\CsvHelper.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\CsvColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\pluginsx86\CsvColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\de\CsvColumnizer.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\pluginsx86\de\CsvColumnizer.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\plugins\CsvColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\pluginsx86\CsvColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#ReleaseFolder}\plugins\AutoColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\AutoColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#ReleaseFolder}\plugins\de\ColumnizerLib.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\plugins\ColumnizerLib.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\plugins\ColumnizerLib.xml"; DestDir: "{app}\plugins\"; Flags: ignoreversion

Source: "{#ReleaseFolder}\pluginsx86\de\ColumnizerLib.resources.dll"; DestDir: "{app}\pluginsx86\de\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\pluginsx86\ColumnizerLib.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\pluginsx86\ColumnizerLib.xml"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion

Source: "{#ReleaseFolder}\plugins\BouncyCastle.Cryptography.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\Microsoft.Extensions.DependencyInjection.Abstractions"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\pluginsx86\Microsoft.Extensions.DependencyInjection.Abstractions"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\pluginsx86\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#ReleaseFolder}\plugins\Newtonsoft.Json.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\pluginsx86\Newtonsoft.Json.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#ReleaseFolder}\plugins\Microsoft.Bcl.HashCode.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\Renci.SshNet.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\System.Memory.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\System.Numerics.Vectors.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\System.Threading.Tasks.Extensions.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#ReleaseFolder}\plugins\DefaultPlugins.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\FlashIconHighlighter.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\FlashIconHighlighter.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#ReleaseFolder}\plugins\GlassfishColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\GlassfishColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#ReleaseFolder}\plugins\JsonColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\JsonColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#ReleaseFolder}\plugins\JsonCompactColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\de\JsonCompactColumnizer.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\plugins\JsonCompactColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#ReleaseFolder}\plugins\Log4jXmlColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\de\Log4jXmlColumnizer.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\plugins\Log4jXmlColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#ReleaseFolder}\plugins\RegexColumnizer.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\de\RegexColumnizer.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\plugins\RegexColumnizer.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#ReleaseFolder}\plugins\LogExpert.Core.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion

; DLLS for SFTP Support
Source: "{#ReleaseFolder}\plugins\SftpFileSystem.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\pluginsx86\SftpFileSystem.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\SftpFileSystem.Resources.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\pluginsx86\SftpFileSystem.Resources.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\de\SftpFileSystem.Resources.resources.dll"; DestDir: "{app}\plugins\de\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\pluginsx86\de\SftpFileSystem.Resources.resources.dll"; DestDir: "{app}\pluginsx86\de\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\plugins\SftpFileSystem.manifest.json"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\pluginsx86\SftpFileSystem.manifest.json"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\plugins\Renci.SshNet.dll"; DestDir: "{app}\plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseFolder}\pluginsx86\Renci.SshNet.dll"; DestDir: "{app}\pluginsx86\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#ReleaseFolder}\de\ColumnizerLib.resources.dll"; DestDir: "{app}\de\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\ColumnizerLib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\ColumnizerLib.xml"; DestDir: "{app}"; Flags: ignoreversion

; LogExpert Files
Source: "{#ReleaseFolder}\files\json\usedComponents.json"; DestDir: "{app}\files\json\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\de\LogExpert.Configuration.resources.dll"; DestDir: "{app}\de\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.Configuration.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.UI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.Resources.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\de\LogExpert.Resources.resources.dll"; DestDir: "{app}\de\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.PluginRegistry.dll"; DestDir: "{app}"; Flags: ignoreversion

Source: "{#ReleaseFolder}\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\NuGet.Versioning.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\LogExpert.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\NLog.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Start.cmd"; DestDir: "{app}"; Flags: ignoreversion

; Vanara libs for Pinvoke => https://github.com/dahall/Vanara
Source: "{#ReleaseFolder}\fr\Vanara.Core.resources.dll"; DestDir: "{app}\fr\"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Shared.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.ComCtl32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Cryptography.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Gdi32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Kernel32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Ole.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Rpc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.RstrtMgr.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Security.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.Shell32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.ShlwApi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\Vanara.PInvoke.User32.dll"; DestDir: "{app}"; Flags: ignoreversion

; GUI Libs
Source: "{#ReleaseFolder}\WeifenLuo.WinFormsUI.Docking.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseFolder}\WeifenLuo.WinFormsUI.Docking.ThemeVS2015.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[InstallDelete]
;DELETE ALL DLLs and PDBs and EXEs
Type: files; Name: "{app}\*.dll"
Type: files; Name: "{app}\*.pdb"
Type: files; Name: "{app}\*.exe"

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function InitializeSetup(): Boolean;
var ErrCode: integer;
begin
    if not Dependency_IsNetCoreInstalled('Microsoft.AspNetCore.App', 10, 0, 0) then begin
      if MsgBox('.net 10 64Bit is missing do you want to download it from https://dotnet.microsoft.com/download/dotnet/10.0 ?', mbConfirmation, MB_YESNO) = IDYES then
      begin
        ShellExecAsOriginalUser('open', 'https://dotnet.microsoft.com/download/dotnet/10.0', '', '', SW_SHOW, ewNoWait, ErrCode);
      end;
    end;
    Result := True;
end;