using System.Drawing;

using Newtonsoft.Json;

namespace LogExpert.Core.Entities;

[Serializable]
public class Bookmark
{
    #region cTor

    [JsonConstructor]
    public Bookmark () { }

    //TODO: Bookmarks Text should be Span<T> or Memory<T>
    public Bookmark (int lineNum)
    {
        LineNum = lineNum;
        Text = string.Empty;
        Overlay = new BookmarkOverlay();
    }

    public Bookmark (int lineNum, string comment)
    {
        LineNum = lineNum;
        Text = comment;
        Overlay = new BookmarkOverlay();
    }

    public static Bookmark CreateAutoGenerated (int lineNum, string comment, string sourceHighlightText)
    {
        return new Bookmark(lineNum, comment)
        {
            IsAutoGenerated = true,
            SourceHighlightText = sourceHighlightText
        };
    }

    #endregion

    #region Properties

    public int LineNum { get; set; }

    public string Text { get; set; }

    public BookmarkOverlay Overlay { get; set; }

    /// <summary>
    /// Position offset of the overlay as set by the user by dragging the overlay with the mouse.
    /// </summary>
    public Size OverlayOffset { get; set; }

    /// <summary>
    /// Indicates whether this bookmark was auto-generated by a highlight rule scan.
    /// Auto-generated bookmarks are transient and not persisted to session files.
    /// </summary>
    [JsonIgnore]
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// The search text of the highlight entry that triggered this bookmark.
    /// Used for display in the BookmarkWindow "Source" column.
    /// </summary>
    [JsonIgnore]
    public string SourceHighlightText { get; set; }

    #endregion
}