<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>logexpert.ico</ApplicationIcon>
    <CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
    <DocumentationFile>$(SolutionDir)..\bin\Docs\LogExpert.xml</DocumentationFile>
    <EnableWindowsTargeting>True</EnableWindowsTargeting>
    <ForceDesignerDPIUnaware>True</ForceDesignerDPIUnaware>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
    <OutputPath>$(SolutionDir)..\bin\$(Configuration)</OutputPath>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>False</UseWindowsForms>

    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>false</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Start.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\Nlog.license.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Content Include="logexpert.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NLog" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ColumnizerLib\ColumnizerLib.csproj" />
    <ProjectReference Include="..\LogExpert.Configuration\LogExpert.Configuration.csproj" />
    <ProjectReference Include="..\LogExpert.UI\LogExpert.UI.csproj" />
    <ProjectReference Include="..\PluginRegistry\LogExpert.PluginRegistry.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Controls\LogTabPage.cs" />
    <Compile Remove="DebugWindow.Designer.cs" />
    <Compile Remove="HighlightThread.cs" />
  </ItemGroup>
</Project>
