<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <OutputPath>$(LogExpertPluginsDirectory)</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyTitle>FlashIconHighlighter</AssemblyTitle>
    <RootNamespace>FlashIconHighlighter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vanara.PInvoke.User32" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ColumnizerLib\ColumnizerLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="FlashIconHighlighter.manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
