// <auto-generated/>
// This file is auto-generated during build. Do not edit manually.
// To regenerate, rebuild the project or run the GeneratePluginHashes MSBuild target.

using System.Collections.Generic;

namespace LogExpert.PluginRegistry;

public static partial class PluginValidator
{
    /// <summary>
    /// Gets pre-calculated SHA256 hashes for built-in plugins.
    /// Generated: 2026-06-28 09:32:59 UTC
    /// Configuration: Release
    /// Plugin count: 21
    /// </summary>
    public static Dictionary<string, string> GetBuiltInPluginHashes()
    {
        return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
                         ["AutoColumnizer.dll"] = "4E4E72F809FF516E0C9D4364D009FF5A991712D120CDB6C42D077D7AB50F1373",
            ["BouncyCastle.Cryptography.dll"] = "E5EEAF6D263C493619982FD3638E6135077311D08C961E1FE128F9107D29EBC6",
            ["BouncyCastle.Cryptography.dll (x86)"] = "E5EEAF6D263C493619982FD3638E6135077311D08C961E1FE128F9107D29EBC6",
            ["CsvColumnizer.dll"] = "717367C6704735154E3F00BC78A1BF9078E4D16FBBE1FF13E3E5CEABDC450D4F",
            ["CsvColumnizer.dll (x86)"] = "717367C6704735154E3F00BC78A1BF9078E4D16FBBE1FF13E3E5CEABDC450D4F",
            ["DefaultPlugins.dll"] = "13F18F0780A1D0007CB05B4DE7FB3A52F7D2AB4D00F818DC4CA4002DE8DFAC29",
            ["FlashIconHighlighter.dll"] = "00DDEB0DF8CC5D49661EE56BBF54111639F05C79F2DAC1EBC83F888C13572052",
            ["GlassfishColumnizer.dll"] = "D3CC956DBA2E9475EFD2C4BB7E6D27C901BDAAC5B96FDAE4F8E1AFF8E6238AC5",
            ["JsonColumnizer.dll"] = "A20DE833A5466D319474DABDE3C60BA1ABE7393BBF2942AF4B7C8C79474F75E4",
            ["JsonCompactColumnizer.dll"] = "28E7F6200637CBE8218330904A309DF24E5F54C2F52D29A8A47F02AAD3ED2A19",
            ["Log4jXmlColumnizer.dll"] = "5EFC0F80D9885729493386A91EEF74488719D54BB1E7D0148376E43746C62AC9",
            ["LogExpert.Resources.dll"] = "ADF6AEE4AD64862020ED2B726476C76F2F4466490DE73414B1765F5C92AF6625",
            ["Microsoft.Extensions.DependencyInjection.Abstractions.dll"] = "67FA4325000DB017DC0C35829B416F024F042D24EFB868BCF17A895EE6500A93",
            ["Microsoft.Extensions.DependencyInjection.Abstractions.dll (x86)"] = "67FA4325000DB017DC0C35829B416F024F042D24EFB868BCF17A895EE6500A93",
            ["Microsoft.Extensions.Logging.Abstractions.dll"] = "BB853130F5AFAF335BE7858D661F8212EC653835100F5A4E3AA2C66A4D4F685D",
            ["Microsoft.Extensions.Logging.Abstractions.dll (x86)"] = "BB853130F5AFAF335BE7858D661F8212EC653835100F5A4E3AA2C66A4D4F685D",
            ["RegexColumnizer.dll"] = "85803BF32EB00E6A40ED73ACB93F4ABD4CDEF98088D4512159784D5216F615BC",
            ["SftpFileSystem.dll"] = "066866006839B63FDA94612F6E6A285DF8DEC09722F073DC54D9336AF1898BF1",
            ["SftpFileSystem.dll (x86)"] = "458BD0886FAC8D41ACF2162C153D8B232E0FB334A49789DD9FA9C62CF38E07D5",
            ["SftpFileSystem.Resources.dll"] = "AB8625761F201B5021332A95946D85D7DB773E6E5E6051A38CAFFB1B49F53C1A",
            ["SftpFileSystem.Resources.dll (x86)"] = "AB8625761F201B5021332A95946D85D7DB773E6E5E6051A38CAFFB1B49F53C1A",

        };
    }
}