// <auto-generated/>
// This file is auto-generated during build. Do not edit manually.
// To regenerate, rebuild the project or run the GeneratePluginHashes MSBuild target.

using System.Collections.Generic;

namespace LogExpert.PluginRegistry;

public static partial class PluginValidator
{
    /// <summary>
    /// Gets pre-calculated SHA256 hashes for built-in plugins.
    /// Generated: 2026-03-03 15:55:52 UTC
    /// Configuration: Release
    /// Plugin count: 22
    /// </summary>
    public static Dictionary<string, string> GetBuiltInPluginHashes()
    {
        return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
                         ["AutoColumnizer.dll"] = "5C6BB42AF77043CB962C6BBDA986AD8E30D07CFD141CA49CE9144BDCB7E3C79D",
            ["BouncyCastle.Cryptography.dll"] = "E5EEAF6D263C493619982FD3638E6135077311D08C961E1FE128F9107D29EBC6",
            ["BouncyCastle.Cryptography.dll (x86)"] = "E5EEAF6D263C493619982FD3638E6135077311D08C961E1FE128F9107D29EBC6",
            ["CsvColumnizer.dll"] = "C057EBE9CC5CD80929A9BD95DA49D53058BF34FBED0704CA4984F914D0C2143F",
            ["CsvColumnizer.dll (x86)"] = "C057EBE9CC5CD80929A9BD95DA49D53058BF34FBED0704CA4984F914D0C2143F",
            ["DefaultPlugins.dll"] = "BF56C02A1B4CABC26E8C16ABFA05631CEF029B95B20455630C619DABAC028E05",
            ["FlashIconHighlighter.dll"] = "EB71A88ECC595BEDA0611018016A8E56258D01B79154E22E052121B020B9B3A9",
            ["GlassfishColumnizer.dll"] = "FC3A8883D5E5886969C62241DF0DB7A3280ABEC2CF4116C59F941C656A4C3288",
            ["JsonColumnizer.dll"] = "63669CA676E6010EAD0AF408178EE36D3315C4481E939E42B40D4FA01FD96E79",
            ["JsonCompactColumnizer.dll"] = "FBB0121C6817E8CE3D21822843E54F42806A768E85ECC9FD7995D6FD700B1788",
            ["Log4jXmlColumnizer.dll"] = "CF18068631B69E2F6008FA76055763034F680FD2DD434C3DC021AFF2C8EEE230",
            ["LogExpert.Core.dll"] = "782E86B987078F283987FD264555BA5374A905728991C926271D8B225C81BF6B",
            ["LogExpert.Resources.dll"] = "FA7CFEDA2901909AD92FF9483A0319DC0F04A35321D7FA4824DA823E1CE89484",
            ["Microsoft.Extensions.DependencyInjection.Abstractions.dll"] = "67FA4325000DB017DC0C35829B416F024F042D24EFB868BCF17A895EE6500A93",
            ["Microsoft.Extensions.DependencyInjection.Abstractions.dll (x86)"] = "67FA4325000DB017DC0C35829B416F024F042D24EFB868BCF17A895EE6500A93",
            ["Microsoft.Extensions.Logging.Abstractions.dll"] = "BB853130F5AFAF335BE7858D661F8212EC653835100F5A4E3AA2C66A4D4F685D",
            ["Microsoft.Extensions.Logging.Abstractions.dll (x86)"] = "BB853130F5AFAF335BE7858D661F8212EC653835100F5A4E3AA2C66A4D4F685D",
            ["RegexColumnizer.dll"] = "2A5DBC467D9EB20CE24CAF43C49CE88E74B863586AF85A6F80465398A47CBF9A",
            ["SftpFileSystem.dll"] = "712884F6B17554D46F9612BD69F5ED39175425CD5A5BB94A5CD3BCE6227B7B1A",
            ["SftpFileSystem.dll (x86)"] = "13420B0728E0478FB29E15A33B5EE33A0199C94594E8278C47C0DE6B9A13436B",
            ["SftpFileSystem.Resources.dll"] = "A03DDDAF2DC0B0989B944FE1387DBE5F31A134418F8BF77308A88B6CA0FEAE51",
            ["SftpFileSystem.Resources.dll (x86)"] = "A03DDDAF2DC0B0989B944FE1387DBE5F31A134418F8BF77308A88B6CA0FEAE51",

        };
    }
}