// <auto-generated/>
// This file is auto-generated during build. Do not edit manually.
// To regenerate, rebuild the project or run the GeneratePluginHashes MSBuild target.

using System.Collections.Generic;

namespace LogExpert.PluginRegistry;

public static partial class PluginValidator
{
    /// <summary>
    /// Gets pre-calculated SHA256 hashes for built-in plugins.
    /// Generated: 2026-06-23 12:02:42 UTC
    /// Configuration: Release
    /// Plugin count: 21
    /// </summary>
    public static Dictionary<string, string> GetBuiltInPluginHashes()
    {
        return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
                         ["AutoColumnizer.dll"] = "12A3D9F1FA876A19C1EAF6F7A8DB2808B8CF1FCF042FEF528026A5043DD28B60",
            ["BouncyCastle.Cryptography.dll"] = "E5EEAF6D263C493619982FD3638E6135077311D08C961E1FE128F9107D29EBC6",
            ["BouncyCastle.Cryptography.dll (x86)"] = "E5EEAF6D263C493619982FD3638E6135077311D08C961E1FE128F9107D29EBC6",
            ["CsvColumnizer.dll"] = "B4AC4B42EAD601C1BE752714BEFA1A9F9DC9298EB0451D06703FA1728085C635",
            ["CsvColumnizer.dll (x86)"] = "B4AC4B42EAD601C1BE752714BEFA1A9F9DC9298EB0451D06703FA1728085C635",
            ["DefaultPlugins.dll"] = "55238A04B43BA5469CAF62FE088BC8BA912CE80BD9BFA4891ED0F9BAA5A27BE3",
            ["FlashIconHighlighter.dll"] = "161EB1329B02C6FF2D582015F590E6CF660D010AC6211F0D8B1D21EEE8D04366",
            ["GlassfishColumnizer.dll"] = "674C31A293D85B2C031145F46EA005B5EC594D5FFCD4700C0CFF72282B816220",
            ["JsonColumnizer.dll"] = "8B643226055C37932A09D573C7CB2582A2ECA4E20478294EF4DC456A3645C911",
            ["JsonCompactColumnizer.dll"] = "D9DB69D4B5379AA605540B5B21CA0A22A7DB98C938D3689F0C3BB5CCB85C1635",
            ["Log4jXmlColumnizer.dll"] = "E6A3B18FA8FCD0E9369B9F0583057771C3BAEA50D1DCF47DBCD5B9F8FFF5D090",
            ["LogExpert.Resources.dll"] = "59C2046E8E3B59A7817E05E90DF91BC51402D0BD22761B2F9B39E8BF4F3C7103",
            ["Microsoft.Extensions.DependencyInjection.Abstractions.dll"] = "67FA4325000DB017DC0C35829B416F024F042D24EFB868BCF17A895EE6500A93",
            ["Microsoft.Extensions.DependencyInjection.Abstractions.dll (x86)"] = "67FA4325000DB017DC0C35829B416F024F042D24EFB868BCF17A895EE6500A93",
            ["Microsoft.Extensions.Logging.Abstractions.dll"] = "BB853130F5AFAF335BE7858D661F8212EC653835100F5A4E3AA2C66A4D4F685D",
            ["Microsoft.Extensions.Logging.Abstractions.dll (x86)"] = "BB853130F5AFAF335BE7858D661F8212EC653835100F5A4E3AA2C66A4D4F685D",
            ["RegexColumnizer.dll"] = "48DE9089F0500E25A94BE43D4A7BDA87BCE6EB62DFB2D5E19F6F94262ED50F60",
            ["SftpFileSystem.dll"] = "67CADE8F6D58C13F4B99E3E20D9D2B6A654C176460631EBEB62C59C0731984AF",
            ["SftpFileSystem.dll (x86)"] = "E2B5529F9613880244BF45A57FB7D601E8C179CFB086B6932EFB21580AD91E8C",
            ["SftpFileSystem.Resources.dll"] = "04BF2ADAC7F7C75731F95608A46C767E39BAE2002F21E0BEFD812C1D7381D097",
            ["SftpFileSystem.Resources.dll (x86)"] = "04BF2ADAC7F7C75731F95608A46C767E39BAE2002F21E0BEFD812C1D7381D097",

        };
    }
}