<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>

    <IsTestProject>true</IsTestProject>
    <AssemblyTitle>LogExpert.PluginRegistry.Tests</AssemblyTitle>
    <Company>Microsoft</Company>
    <RootNamespace>LogExpert.PluginRegistry.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PluginRegistry\LogExpert.PluginRegistry.csproj" />
    <ProjectReference Include="..\ColumnizerLib\ColumnizerLib.csproj" />
    <ProjectReference Include="..\LogExpert.Core\LogExpert.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
  </ItemGroup>
</Project>
