//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvColumnizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogExpert.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CsvColumnizerConfigDlg_UI_Button_Cancel {
            get {
                return ResourceManager.GetString("CsvColumnizerConfigDlg_UI_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CsvColumnizerConfigDlg_UI_Button_OK {
            get {
                return ResourceManager.GetString("CsvColumnizerConfigDlg_UI_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First line contains field names.
        /// </summary>
        public static string CsvColumnizerConfigDlg_UI_CheckBox_FirstLineFieldNames {
            get {
                return ResourceManager.GetString("CsvColumnizerConfigDlg_UI_CheckBox_FirstLineFieldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use escape chars.
        /// </summary>
        public static string CsvColumnizerConfigDlg_UI_CheckBox_UseEscapeChars {
            get {
                return ResourceManager.GetString("CsvColumnizerConfigDlg_UI_CheckBox_UseEscapeChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment char:.
        /// </summary>
        public static string CsvColumnizerConfigDlg_UI_Label_CommentChar {
            get {
                return ResourceManager.GetString("CsvColumnizerConfigDlg_UI_Label_CommentChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter char:.
        /// </summary>
        public static string CsvColumnizerConfigDlg_UI_Label_DelimiterChar {
            get {
                return ResourceManager.GetString("CsvColumnizerConfigDlg_UI_Label_DelimiterChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape char:.
        /// </summary>
        public static string CsvColumnizerConfigDlg_UI_Label_EscapeChar {
            get {
                return ResourceManager.GetString("CsvColumnizerConfigDlg_UI_Label_EscapeChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min columns.
        /// </summary>
        public static string CsvColumnizerConfigDlg_UI_Label_MinColumns {
            get {
                return ResourceManager.GetString("CsvColumnizerConfigDlg_UI_Label_MinColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (0 = no minimum check).
        /// </summary>
        public static string CsvColumnizerConfigDlg_UI_Label_MinColumnsInfo {
            get {
                return ResourceManager.GetString("CsvColumnizerConfigDlg_UI_Label_MinColumnsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote char:.
        /// </summary>
        public static string CsvColumnizerConfigDlg_UI_Label_QuoteChar {
            get {
                return ResourceManager.GetString("CsvColumnizerConfigDlg_UI_Label_QuoteChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Columnizer Configuration.
        /// </summary>
        public static string CsvColumnizerConfigDlg_UI_Title {
            get {
                return ResourceManager.GetString("CsvColumnizerConfigDlg_UI_Title", resourceCulture);
            }
        }
    }
}
