<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="chocolatey" Version="2.4.3" />
    <PackageVersion Include="CsvHelper" Version="33.1.0" />
    <PackageVersion Include="DockPanelSuite.ThemeVS2015" Version="3.1.1" />
    <PackageVersion Include="GitVersion.Core" Version="6.3.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="NLog" Version="6.0.6" />
    <PackageVersion Include="NuGet.CommandLine" Version="6.14.0" />
    <PackageVersion Include="NuGet.Versioning" Version="7.0.0" />
    <PackageVersion Include="Nuke.Common" Version="9.0.4" />
    <PackageVersion Include="Nuke.GitHub" Version="7.0.0" />
    <PackageVersion Include="NUnit" Version="4.4.0" />
    <PackageVersion Include="NUnit.ConsoleRunner" Version="3.20.1" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.2.0" />
    <PackageVersion Include="SSH.NET" Version="2025.1.0" />
    <PackageVersion Include="System.Drawing.Common" Version="10.0.0" />
    <PackageVersion Include="System.Resources.Extensions" Version="10.0.0" />
  </ItemGroup>
</Project>