using ColumnizerLib;

using LogExpert.Core.Classes.Bookmark;
using LogExpert.Core.Classes.Highlight;

using NUnit.Framework;

namespace LogExpert.Tests.Bookmark;

[TestFixture]
public class HighlightBookmarkScannerTests
{

    [SetUp]
    public void SetUp ()
    {
    }

    #region Helper

    /// <summary>
    /// Simple ILogLineMemory implementation for testing.
    /// </summary>
    private class TestLogLine : ILogLineMemory
    {
        private readonly string _text;

        public TestLogLine (string text, int lineNumber)
        {
            _text = text;
            LineNumber = lineNumber;
        }

        public ReadOnlyMemory<char> FullLine => _text.AsMemory();
        public ReadOnlyMemory<char> Text => _text.AsMemory();
        public int LineNumber { get; }
    }

    private static ILogLineMemory MakeLine (string text, int lineNum) => new TestLogLine(text, lineNum);

    #endregion

    [Test]
    public void Scan_NoBookmarkEntries_ReturnsEmpty ()
    {
        // Arrange
        var entries = new List<HighlightEntry>
        {
            new() { SearchText = "ERROR", IsSetBookmark = false }
        };

        // Act
        var result = HighlightBookmarkScanner.Scan(3, i => MakeLine($"Line {i} ERROR", i), entries, "test.log");

        // Assert
        Assert.That(result, Is.Empty);
    }

    [Test]
    public void Scan_SingleMatch_ReturnsOneBookmark ()
    {
        // Arrange
        var entries = new List<HighlightEntry>
        {
            new() { SearchText = "ERROR", IsSetBookmark = true, BookmarkComment = "Found error" }
        };
        var lines = new[] { "INFO starting", "ERROR something failed", "INFO done" };

        // Act
        var result = HighlightBookmarkScanner.Scan(3, i => MakeLine(lines[i], i), entries, "test.log");

        // Assert
        Assert.That(result, Has.Count.EqualTo(1));
        Assert.That(result[0].LineNum, Is.EqualTo(1));
        Assert.That(result[0].IsAutoGenerated, Is.True);
        Assert.That(result[0].SourceHighlightText, Is.EqualTo("ERROR"));
        Assert.That(result[0].Text, Is.EqualTo("Found error"));
    }

    [Test]
    public void Scan_MultipleMatches_ReturnsMultipleBookmarks ()
    {
        // Arrange
        var entries = new List<HighlightEntry>
        {
            new() { SearchText = "ERROR", IsSetBookmark = true, BookmarkComment = "" }
        };
        var lines = new[] { "ERROR first", "INFO ok", "ERROR second" };

        // Act
        var result = HighlightBookmarkScanner.Scan(3, i => MakeLine(lines[i], i), entries, "test.log");

        // Assert
        Assert.That(result, Has.Count.EqualTo(2));
        Assert.That(result[0].LineNum, Is.EqualTo(0));
        Assert.That(result[1].LineNum, Is.EqualTo(2));
    }

    [Test]
    public void Scan_NoMatches_ReturnsEmpty ()
    {
        // Arrange
        var entries = new List<HighlightEntry>
        {
            new() { SearchText = "FATAL", IsSetBookmark = true }
        };
        var lines = new[] { "INFO ok", "DEBUG trace" };

        // Act
        var result = HighlightBookmarkScanner.Scan(2, i => MakeLine(lines[i], i), entries, "test.log");

        // Assert
        Assert.That(result, Is.Empty);
    }

    [Test]
    public void Scan_CaseInsensitiveMatch_Works ()
    {
        // Arrange
        var entries = new List<HighlightEntry>
        {
            new() { SearchText = "error", IsSetBookmark = true, IsCaseSensitive = false }
        };
        var lines = new[] { "ERROR something" };

        // Act
        var result = HighlightBookmarkScanner.Scan(1, i => MakeLine(lines[i], i), entries, "test.log");

        // Assert
        Assert.That(result, Has.Count.EqualTo(1));
    }

    [Test]
    public void Scan_CaseSensitiveMatch_RespectsCase ()
    {
        // Arrange
        var entries = new List<HighlightEntry>
        {
            new() { SearchText = "error", IsSetBookmark = true, IsCaseSensitive = true }
        };
        var lines = new[] { "ERROR something" };

        // Act
        var result = HighlightBookmarkScanner.Scan(1, i => MakeLine(lines[i], i), entries, "test.log");

        // Assert
        Assert.That(result, Is.Empty);
    }

    [Test]
    public void Scan_RegexMatch_Works ()
    {
        // Arrange
        var entries = new List<HighlightEntry>
        {
            new() { SearchText = "ERR\\w+", IsSetBookmark = true, IsRegex = true }
        };
        var lines = new[] { "ERROR something" };

        // Act
        var result = HighlightBookmarkScanner.Scan(1, i => MakeLine(lines[i], i), entries, "test.log");

        // Assert
        Assert.That(result, Has.Count.EqualTo(1));
    }

    [Test]
    public void Scan_MultipleEntries_OnlyBookmarkEntriesUsed ()
    {
        // Arrange
        var entries = new List<HighlightEntry>
        {
            new() { SearchText = "ERROR", IsSetBookmark = true, BookmarkComment = "err" },
            new() { SearchText = "WARN", IsSetBookmark = false },  // not a bookmark entry
            new() { SearchText = "FATAL", IsSetBookmark = true, BookmarkComment = "fatal" }
        };
        var lines = new[] { "ERROR happened", "WARN ignored", "FATAL crash" };

        // Act
        var result = HighlightBookmarkScanner.Scan(3, i => MakeLine(lines[i], i), entries, "test.log");

        // Assert
        Assert.That(result, Has.Count.EqualTo(2));
        Assert.That(result[0].LineNum, Is.EqualTo(0));
        Assert.That(result[0].SourceHighlightText, Is.EqualTo("ERROR"));
        Assert.That(result[1].LineNum, Is.EqualTo(2));
        Assert.That(result[1].SourceHighlightText, Is.EqualTo("FATAL"));
    }

    [Test]
    public void Scan_NullLine_Skipped ()
    {
        // Arrange
        var entries = new List<HighlightEntry>
        {
            new() { SearchText = "ERROR", IsSetBookmark = true }
        };

        // Act — line 1 returns null
        var result = HighlightBookmarkScanner.Scan(3, i => i == 1 ? null : MakeLine("ERROR text", i), entries, "test.log");

        // Assert — only lines 0 and 2 produce bookmarks
        Assert.That(result, Has.Count.EqualTo(2));
        Assert.That(result[0].LineNum, Is.EqualTo(0));
        Assert.That(result[1].LineNum, Is.EqualTo(2));
    }

    [Test]
    public void Scan_CancellationRequested_ThrowsOperationCanceled ()
    {
        // Arrange
        var entries = new List<HighlightEntry>
        {
            new() { SearchText = "ERROR", IsSetBookmark = true }
        };

        using var cts = new CancellationTokenSource();
        cts.Cancel();

        // Act & Assert
        _ = Assert.Throws<OperationCanceledException>(() => HighlightBookmarkScanner.Scan(100, i => MakeLine("ERROR text", i), entries, "test.log", cancellationToken: cts.Token));
    }

    [Test]
    public void Scan_ReportsProgress ()
    {
        // Arrange
        var entries = new List<HighlightEntry>
        {
            new() { SearchText = "x", IsSetBookmark = true }
        };
        var reported = new List<int>();
        var progress = new Progress<int>(reported.Add);

        // Act — use synchronous progress to capture values
        // Note: Progress<T> posts to SynchronizationContext, so for test we use a simple impl
        var syncProgress = new SyncProgress<int>(reported);
        _ = HighlightBookmarkScanner.Scan(3, i => MakeLine("x", i), entries, "test.log", 1, syncProgress, CancellationToken.None);

        // Assert
        Assert.That(reported, Is.EqualTo([0, 1, 2]));
    }

    [Test]
    public void Scan_ZeroLines_ReturnsEmpty ()
    {
        // Arrange
        var entries = new List<HighlightEntry>
        {
            new() { SearchText = "ERROR", IsSetBookmark = true }
        };

        // Act
        var result = HighlightBookmarkScanner.Scan(0, _ => null, entries, "test.log");

        // Assert
        Assert.That(result, Is.Empty);
    }

    #region Helper classes

    /// <summary>
    /// Synchronous IProgress implementation for testing (avoids SynchronizationContext issues).
    /// </summary>
    private class SyncProgress<T> (List<T> values) : IProgress<T>
    {
        private readonly List<T> _values = values;

        public void Report (T value) => _values.Add(value);
    }

    #endregion
}